# Generated by Django 3.2.18 on 2023-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatioalmodules',
            name='description',
            field=models.TextField(verbose_name='Опиасание образовательного модуля'),
        ),
        migrations.AlterField(
            model_name='educatioalmodules',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название образовательного модуля'),
        ),
        migrations.AlterField(
            model_name='educatioalmodules',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Порядковый номер'),
        ),
    ]
