# Generated by Django 3.2.18 on 2023-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20230421_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducatioalModules',
            new_name='EducationalModules',
        ),
    ]
